/**:
  ros__parameters:
    visualize: true
    use_fitness_based_calibration: false
    # Topics for all lidars
    lidar_topics: [ouster, front, right, left]
    table_degrees: false
    read_tf_from_table: true

    # table of lidar name (frame_id in ROS), xyz translation [m], rpy rotation [deg/rad]
    ouster: [4.446, 0.02, 1.347, -0.018569, 0.01447, -0.014]
    front: [2.319, 0.00268, 0.68636, -0.37546573, -1.5461567, -2.7650]
    left: [1.76349, 0.12679, 0.7449607,-1.7899759, -1.5592, 0.7437]
    right: [1.7286966, -0.11475, 0.76980, 2.916668, -1.564541, -1.86865887]
    

    # egyszer mar mukodott setup:
    # OUSTER FRAME:
    # ouster: [0.0, 0.0, -0.35, 0.05, -0.011, -0.020]
    # front: [-2.13178446, -0.028217539, -1.065434, -1.02060464, -1.4818257, -2.1205372]

    # VEHICLE FRAME:
    # ouster: [4.438, 0.0, 1.27, -0.019, 0.016, -0.01]
    # front: [2.308, 0.0, 0.70375, -0.14336, -1.5501101979999987, -2.994086805]


    target_frame_id: ouster
    base_frame_id: vehicle
    calibrate_to_base: true
    calibrate_target: false
    calibrate_roll_pitch_after_to_base_transform: true

    # path for point clouds in pcd format. Structure: /pcd_directory/<lidar_name>.pcd
    pcd_directory: /../data/LC03/

    # logging output
    results_file: LC03_results.txt
    remove_ground_flag: false

    # calibration results are stored here (path relative to the dir with multi_lidar_calibrator.py)
    output_dir: /../output/
